### ISSUE TITLE
Problem using Certify with separate CFSSL in GOPATH

### ISSUE THREAD

**Issue by Southclaws** [johanbrandhorst/certify#45]
This is a repository-level issue that's causing a problem with our tooling.

This is output by the vscode static analysis tools as well as non-Go 1.11 module builds (within Gopath, with GO111MODULE=off/auto). The actual application builds on our CI because we use Go 1.11 modules for that. However, this breaks all intellisense features because every other issue is ignored and this is the only output:

```
cannot use caAuth (type *"github.com/cloudflare/cfssl/auth".Standard) as type "github.com/johanbrandhorst/certify/vendor/github.com/cloudflare/cfssl/auth".Provider in field value:
	*"github.com/cloudflare/cfssl/auth".Standard does not implement "github.com/johanbrandhorst/certify/vendor/github.com/cloudflare/cfssl/auth".Provider (wrong type for Verify method)
		have Verify(*"github.com/cloudflare/cfssl/auth".AuthenticatedRequest) bool
		want Verify(*"github.com/johanbrandhorst/certify/vendor/github.com/cloudflare/cfssl/auth".AuthenticatedRequest) bool
```

It's my understanding that vendor/ paths should not be used by library authors and only for end-user binaries.

Given that this project already specifies go.mod/go.sum for proper version management - it would make sense to simply remove the vendor directory to resolve these issues with vscode tooling. As right now, I think the only alternative is to run the static analysis tools manually and ignore vscode - which is pretty annoying!

**Comment by johanbrandhorst** [comment]
Hi @Southclaws. Thanks for raising this issue. I'm sorry to hear it has broken your CI testing. However, I was under the impression the advice against library authors using vendor folders is not really relevant anymore, and certainly not if your clients are using go modules. Do you have a recent reference for this advice?

As for your problem, I think this is not because of your VSCode but because your dependency manager (presumably `dep`) doesn't support parsing go.mod for dependency versions yet. You can fix this with an explicit version override. Are you using dep?

**Comment by johanbrandhorst** [comment]
Also I'm not sure removing the vendor folder from this repo would fix your issue.

**Comment by johanbrandhorst** [comment]
Actually, looking a little bit closer at this error, what I think is happening here is that you're using `Certify` in an environment where your `$GOPATH` has a separate checkout of `github.com/cloudflare/cfssl`. The error has nothing to do with the vendoring of Certify, it's a type incompatibility between versions in your $GOPATH and your vendor folder. Try removing `github.com/cloudflare/cfssl` from your GOPATH and make sure Certify is in your vendor folder and it should work again.

I'll leave this issue open for a few days in case you have more questions, but it might be easiest to reach out to me on gophers slack otherwise (`jbrandhorst`).

**Comment by Southclaws** [comment]
No, not using dep, using Go 1.11 modules - the build works if outside the GOPATH or with GO111MODULE=on but not without this. This is fine for building the binary but it breaks all the tooling still.

Removing those directories from the GOPATH won't work because then imports will fail:

```
cannot find package "github.com/cloudflare/cfssl/api/client" in any of:
	/usr/local/Cellar/go/1.11/libexec/src/github.com/cloudflare/cfssl/api/client (from $GOROOT)
	/Users/barnabykeene/go/src/github.com/cloudflare/cfssl/api/client (from $GOPATH)
```

Deleting the `vendor/` directory from my local GOPATH copy of certify did fix the issue. I know this is an odd edge case but surely I can't be the only one who uses vscode and this library. If you don't want to remove the old vendor dir I'll just keep my local copy modified with the directory removed.

**Comment by johanbrandhorst** [comment]
I think I'm starting to see why you're having a problem here. Correct me if any of the following is wrong:

1. You're using the GOPATH in your local development environment.
2. You're using `go modules` in your CI environment.
3. Because of #2, you're choosing not to use a vendor folder but relying on `go get` to install dependencies into your GOPATH locally.

If all of the above is true, you've got a toxic local development setup. Not using `go modules` locally will prevent you from using the correct dependency versions when building, and might even produce different behaviour from your CI environment. There are two ways you could prevent this from happening:

1. Vendor locally based on the `go.mod` file. This is as simple as running `GO111MODULE=on go mod vendor` in your workspace. This would probably be combined with a `.gitignore` file that ignores `vendor/` so you don't check it in by mistake.
2. Just use `go modules` even inside the GOPATH. Again, this can be turned on with the environment variable.

Now, as I believe you're right in saying that you can't be alone experiencing problems like this I will probably go and remove the vendor folder from this repo, but hopefully this issue can stand as a guide to others about improving their local development environment instead of relying on library authors to implement work arounds for dangerous setups.

FWIW I am also using VSCode to develop this library. This issue has little to do with that.

Does that sound about right?

**Comment by Southclaws** [comment]
So this is what my local dev actually looks like:
- Using `GOPATH` to *store* code
- Using Go 1.11 modules for all our internal dependencies
- Using `GO111MODULE=on` for builds

The reason for this is the tooling hasn't quite caught up to 1.11 modules yet - so the intellisense and linting features *still* rely on GOPATH packages, if you try and use modules the tooling literally takes 5 minutes to run and all fans spin up, it's a mess.

So, what's happening here is the intellisense tooling is searching GOPATH for packages to build the AST for type hints and all that good stuff, it's hitting this package and using the vendor directory for its local imports. Then, because our codebase *also* imports cfssl packages, these import paths don't match up.

Now, the only ways I've solved this so far is:
- Force the tooling to use modules - takes 5 minutes and my laptop sounds like a jet engine
- Delete the vendor directory in this repo's GOPATH copy (not the module cache) - this works fine for now, I'm happy with this solution so you don't need to do anything and can close this issue and hopefully this bug gets resolved in the tooling
- Set my import path for cfssl explicitly to use the vendored version from this repo

**Comment by johanbrandhorst** [comment]
I will remove the vendor dir because it should be reasonably easy to work around the CI reasons for why it's there, but I think you should also be able to solve this by just explicitly vendoring your stuff in your _workspace_. Relying on the GOPATH for versioning anything is dangerous.
